name: Release Single Image
on:
  workflow_dispatch:
    inputs:
      pipeline-argument:
        description: 'Argument to pass to pipeline'
        required: true
      release-key:
        description: 'Corresponding release.json key'
        required: true
jobs:
  release-single-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: "Release Image"
        uses: ./.github/actions/release-image
        with:
          pipeline-argument: ${{ github.event.inputs.pipeline-argument }}
          release-key: ${{ github.event.inputs.release-key }}
